[package]
name = "nmt_terminal"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[features]
default = ["wayland", "x11"]
x11 = [
    "nmt_platform/x11"
]
wayland = [
    "nmt_platform/wayland",
]

test-support = []

[dependencies]
libghostty-vt-sys.workspace = true
nmt_config.workspace = true
nmt_input.workspace = true
nmt_platform = { workspace = true, features = ["clipboard"] }

base64.workspace = true
bitflags.workspace = true
image_rs.workspace = true
memchr.workspace = true
parking_lot.workspace = true
rustc-hash.workspace = true
tracing.workspace = true
futures.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }

[target.'cfg(enable_profiling)'.dependencies]
nmt_profiling.workspace = true
