[package]
name = "nmt_shell_extension"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[lib]
name = "shell_extension"
crate-type = ["cdylib"]

[dependencies]
percent-encoding = { workspace = true }
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
] }
windows-core = { workspace = true }

[build-dependencies]
nmt_build_version.workspace = true
winres.workspace = true
