[package]
name = "nmt_config"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[features]
default = ["application"]
application = [
    "dep:nmt_profile",
    "dep:dirs",
    "dep:toml",
    "dep:toml_edit",
    "dep:nmt_platform",
    "dep:tempfile",
]

[dependencies]
dirs = { workspace = true, optional = true }
serde.workspace = true
toml = { workspace = true, optional = true }
toml_edit = { workspace = true, optional = true }
tracing.workspace = true
nmt_platform = { workspace = true, optional = true }
tempfile = { workspace = true, optional = true }
nmt_profile = { workspace = true, optional = true }
