use gpui::actions;

actions!(
    NiumaTerm,
    [
        NewTab,
        CloseTab,
        NextTab,
        PrevTab,
        NewWorkspace,
        NextWorkspace,
        PrevWorkspace,
        NewWindow,
        SplitUp,
        SplitDown,
        SplitLeft,
        SplitRight,
        ResizePaneUp,
        ResizePaneDown,
        ResizePaneLeft,
        ResizePaneRight,
        ToggleSidebar,
        ToggleGitSidebar,
        ToggleBackgroundTasks,
        ToggleWorkflows,
        ShowSettings,
        NewRemoteTab,
        NewAgentTab,
    ]
);
