[package]
name = "nmt_remote_session_hub"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[target.'cfg(windows)'.dependencies]
nmt_config.workspace = true
nmt_platform.workspace = true
nmt_terminal.workspace = true
parking_lot.workspace = true
serde.workspace = true
