[package]
name = "nmt_agent_utils"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
base64.workspace = true
chrono.workspace = true
getrandom.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
uuid.workspace = true

[target.'cfg(windows)'.dependencies]
reqwest = { workspace = true, features = [
    "blocking",
    "rustls-tls-native-roots",
    "system-proxy",
] }
windows-sys.workspace = true
