[package]
name = "nmt_agent_utils"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
base64.workspace = true
chrono.workspace = true
getrandom.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true
semver.workspace = true
sha2.workspace = true
tracing.workspace = true
uuid.workspace = true
which.workspace = true

[target.'cfg(windows)'.dependencies]
nmt_platform.workspace = true
reqwest = { workspace = true, features = [
    "blocking",
    "rustls-tls-native-roots",
    "system-proxy",
] }
tungstenite.workspace = true
windows-sys.workspace = true
