[package]
name = "nmt_remote_net"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
base32.workspace = true
futures.workspace = true
parking_lot.workspace = true
postcard.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
snow.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tracing.workspace = true

[target.'cfg(windows)'.dependencies]
nmt_platform.workspace = true
nmt_remote_session_hub.workspace = true
